# Generated by Django 3.2.3 on 2021-05-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_braintree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(max_length=5),
        ),
    ]
